# Generated by Django 4.0.4 on 2022-05-31 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0002_company_owner_alter_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('N', 'Не ищу работу'), ('L', 'Рассматриваю предложения'), ('Y', 'Ищу работу')], default='Y', max_length=1)),
                ('salary', models.IntegerField()),
                ('specialty', models.CharField(max_length=64)),
                ('grade', models.CharField(choices=[('INT', 'Стажер'), ('JUN', 'Джуниор'), ('MID', 'Миддл'), ('SEN', 'Сеньор'), ('LED', 'Лид')], default='JUN', max_length=3)),
                ('education', models.CharField(max_length=256)),
                ('experience', models.TextField()),
                ('portfolio', models.CharField(max_length=256)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
